name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Bootstrap
        shell: bash
        run: bash scripts/bootstrap.sh || true
      - name: Verify
        shell: bash
        run: bash scripts/verify.sh || true
      - name: Show artifacts
        if: always()
        shell: bash
        run: |
          echo "Current directory:"
          pwd || true
          echo "All files:"
          ls -la || true
          echo "Reports directory:"
          ls -la reports 2>/dev/null || echo "No reports directory"
          echo "Reports content:"
          tail -n +1 reports/*.log 2>/dev/null || echo "No log files"
          exit 0
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
          if-no-files-found: warn
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**
          if-no-files-found: warn
