name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  verify-cpu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
      - name: Install deps (CPU)
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
          pip install -f https://download.pytorch.org/whl/cpu/torch_stable.html torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 || true
      - name: Verify
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            powershell -File scripts/verify.ps1
          else
            bash scripts/verify.sh
          fi
      - name: Upload reports and coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cpu-verify-artifacts
          path: |
            reports/*.log
            coverage.xml
          if-no-files-found: warn
          retention-days: 30
      - name: Enforce green gates
        run: |
          tail -n +1 reports/*.log || true
          grep -q "ALL GATES PASSED" reports/tests.log


